% Yande Liu's System ID Model
% Model of Vehicle Dynamics and Ardupilot ATT controller using system ID

% System ID was performed using Pilot RC Input data (Desired Attitude)
% and Vehicle State (Velocity and Attitude)
%% Setup State Space Model
% Lateral Dynamics
% States are: [lateral velocity, roll angle, integral of moment of rate,
% and integrator compensation for attitude]
Alat = [-0.1180 32.033 0 0;
       0 -6.411 1 0;
       0 -20.639 0 1;
       0 -1.235 0 0];
Blat = [0; 
        0.0039974;
        0.016275;
        0.0040072];
Clat = [0.3048 0 0 0];
Dlat = 0;

sys_lat_vel = ss(Alat, Blat, Clat, Dlat);

%% Lateral Transfer Function
% include the time delay generated by CIFER
lat_time_delay = 0.156; % (in seconds)

% U(s) = desired roll (pwm), Y(s) = Vehicle Velocity
[NUM, DEN] = ss2tf(Alat, Blat, Clat, Dlat);
sys_lat_tf_vel = tf(NUM, DEN, 'InputDelay', lat_time_delay);
g = tf(NUM, DEN);

%%
% U(s) = desired roll (pwm), Y(s) = Vehicle Attitude
C = [0 1 0 0];
[NUMr, DENr] = ss2tf(Alat, Blat, C, Dlat);
sys_lat_tf_roll = tf(NUMr, DENr, 'InputDelay', lat_time_delay);

%% Analysis of System

% Linear Simulation Response
% Generate some input (two steps)
% System is trimmed with PWM at 1500
% Model is detrended so 1500 is max and 0 is trim
[u,t] = gensig('square',5,10,0.1);
figure(1);
lsim(sys_lat_tf_vel, u*1500, t,0)
title("lateral velocity response")
figure(2);
lsim(sys_lat_tf_roll, u*1500, t,0)
title("roll angle response")



%% Model verification using flight log data

% Load a log and get input and output data
% Will need RCIN Channel 1 and NKF1 VE (Lateral Velocity) data
[file, path] = uigetfile
load(strcat(path, file));

RCIN_TIME = RCIN(:,2);
RCIN_DATA = RCIN(:,4);

VE_TIME = NKF1(:,2);
VE_DATA = NKF1(:,7);
% From ID data object and then we can compare
% Sampling rate is 10 Hz for both systems
measured_data = iddata(VE_DATA, RCIN_DATA, 0.1)
figure(5)
plot(measured_data)


%%
systemIdentification

%%
%
P_Gain = 35.524;
